version: "3.8"

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://delta_admin:delta_password@mongo:27017
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=delta_admin
      - MONGO_INITDB_ROOT_PASSWORD=delta_password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: delta_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: delta_password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_OPTIONS_EDITORTHEME: dark
      ME_CONFIG_SITE_BASEURL: "/"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
